In [1]:
import numpy as np
import pandas as pd
from scipy.stats import binom

In [6]:
r0 = 0.05
U = 1.1
D = 0.9
Q = 0.5

Q1 
1.construct interest binomial lattice

In [13]:
def interest_lattice(r,u,d,q,T):
    lattice = pd.DataFrame()
    for i in range(T+1):
        interest_period = np.zeros(T+1)
        for j in range(i+1):
            interest_period[j] = r * d**j * u**(i-j)
        lattice[i] = interest_period
    return lattice

In [14]:
interest_lattice(r0,U,D,Q,10)

,0,1,2,3,4,5,6,7,8,9,10
0,0.05,0.055,0.0605,0.06655,0.073205,0.080526,0.088578,0.097436,0.107179,0.117897,0.129687
1,0.00,0.045,0.0495,0.05445,0.059895,0.065885,0.072473,0.079720,0.087692,0.096461,0.106108
2,0.00,0.000,0.0405,0.04455,0.049005,0.053906,0.059296,0.065226,0.071748,0.078923,0.086815
3,0.00,0.000,0.0000,0.03645,0.040095,0.044105,0.048515,0.053366,0.058703,0.064573,0.071031
4,0.00,0.000,0.0000,0.00000,0.032805,0.036086,0.039694,0.043663,0.048030,0.052833,0.058116
5,0.00,0.000,0.0000,0.00000,0.000000,0.029525,0.032477,0.035725,0.039297,0.043227,0.047550
6,0.00,0.000,0.0000,0.00000,0.000000,0.000000,0.026572,0.029229,0.032152,0.035367,0.038904
7,0.00,0.000,0.0000,0.00000,0.000000,0.000000,0.000000,0.023915,0.026306,0.028937,0.031831
8,0.00,0.000,0.0000,0.00000,0.000000,0.000000,0.000000,0.000000,0.021523,0.023676,0.026043
9,0.00,0.000,0.0000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019371,0.021308
10,0.00,0.000,0.0000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017434